# Generated by Django 3.2.3 on 2021-08-06 06:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='company',
            table='Company',
        ),
        migrations.AlterModelTable(
            name='usercompanyrole',
            table='UserCompanyRole',
        ),
    ]
