# Generated by Django 3.2.3 on 2021-08-16 07:23

from django.db import migrations, models
import django.db.models.deletion
import organization.models


class Migration(migrations.Migration):

    dependencies = [
        ('usermanagement', '0004_accessrequest_skill_sets'),
        ('organization', '0002_auto_20210806_1155'),
    ]

    operations = [
        migrations.CreateModel(
            name='CompanyInfo',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('logo', models.ImageField(blank=True, null=True, upload_to=organization.models.get_file_path)),
                ('corporate_type', models.CharField(blank=True, max_length=1000, null=True)),
                ('emploay_size', models.CharField(blank=True, max_length=100, null=True)),
                ('type', models.CharField(blank=True, max_length=100, null=True)),
                ('links', models.CharField(blank=True, max_length=100, null=True)),
                ('about', models.CharField(blank=True, max_length=100, null=True)),
                ('active', models.BooleanField(default=1)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('company', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='organization.company')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='companyinfo_created_by', to='usermanagement.users')),
                ('updated_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='companyinfo_updated_by', to='usermanagement.users')),
            ],
            options={
                'db_table': 'CompanyInfo',
            },
        ),
    ]
