# Generated by Django 3.2.3 on 2021-08-16 09:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0003_companyinfo'),
    ]

    operations = [
        migrations.RenameField(
            model_name='companyinfo',
            old_name='emploay_size',
            new_name='number_of_emploies',
        ),
    ]
