# Generated by Django 3.2.3 on 2021-08-20 10:12

from django.db import migrations, models
import organization.models


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0004_rename_emploay_size_companyinfo_number_of_emploies'),
    ]

    operations = [
        migrations.AlterField(
            model_name='companyinfo',
            name='logo',
            field=models.FileField(blank=True, null=True, upload_to=organization.models.get_file_path),
        ),
    ]
