# Generated by Django 3.2.3 on 2021-08-20 10:20

from django.db import migrations, models
import organization.models


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0005_alter_companyinfo_logo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='companyinfo',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to=organization.models.get_file_path),
        ),
    ]
