# Generated by Django 3.2.3 on 2021-08-05 01:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usermanagement', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AccessRequest',
            fields=[
                ('id', models.AutoField(db_column='id', primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(db_column='Name of Worker', max_length=200)),
                ('email', models.CharField(db_column='Email', max_length=250)),
                ('company_name', models.CharField(blank=True, db_column='Company Name', max_length=500)),
                ('phone_number', models.CharField(blank=True, db_column='Ph.No', max_length=13, null=True)),
                ('skill_sets', models.TextField(blank=True, db_column='Skill Sets', null=True)),
                ('active', models.BooleanField(default=True)),
                ('pending_status', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'AccessRequest',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Workers',
            fields=[
                ('id', models.AutoField(db_column='id', primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(db_column='Name of Worker', max_length=200)),
                ('email', models.CharField(db_column='Email', max_length=250)),
                ('phone_no', models.CharField(blank=True, db_column='Ph.No', max_length=13, null=True)),
                ('active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'Workers',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AlterModelTable(
            name='accessmanagement',
            table='AccessManagement',
        ),
        migrations.AlterModelTable(
            name='activitylogs',
            table='ActivityLogs',
        ),
        migrations.AlterModelTable(
            name='roles',
            table='Roles',
        ),
        migrations.AlterModelTable(
            name='temporaryurl',
            table='TemporaryUrl',
        ),
        migrations.AlterModelTable(
            name='users',
            table='Users',
        ),
    ]
