# Generated by Django 3.2.3 on 2021-08-16 07:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usermanagement', '0003_auto_20210811_1125'),
    ]

    operations = [
        migrations.AddField(
            model_name='accessrequest',
            name='skill_sets',
            field=models.TextField(blank=True, db_column='Skill Sets', null=True),
        ),
    ]
