# Generated by Django 3.1.2 on 2020-10-12 18:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0003_projectusers_expiry_date'),
    ]

    operations = [
        migrations.RenameField(
            model_name='getprogress',
            old_name='get_training_logs',
            new_name='base_file_upload',
        ),
    ]
