# Generated by Django 3.1.2 on 2020-10-15 16:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0004_auto_20201012_1851'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectinfo',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
