# Generated by Django 3.2.3 on 2021-08-13 04:58

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0006_auto_20210806_1154'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectinfo',
            name='catagory',
            field=models.CharField(default='catagory1', max_length=300),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='projectinfo',
            name='end_date',
            field=models.DateField(auto_now_add=True, default=datetime.datetime(2021, 8, 13, 4, 56, 59, 409842, tzinfo=utc)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='projectinfo',
            name='end_time',
            field=models.TimeField(default=datetime.datetime(2021, 8, 13, 4, 57, 18, 592900, tzinfo=utc)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='projectinfo',
            name='publish',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='projectinfo',
            name='salary_from',
            field=models.IntegerField(default=2300),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='projectinfo',
            name='salary_to',
            field=models.IntegerField(default=2500),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='projectinfo',
            name='start_date',
            field=models.DateField(auto_now_add=True, default=datetime.datetime(2021, 8, 13, 4, 57, 55, 497299, tzinfo=utc)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='projectinfo',
            name='start_time',
            field=models.TimeField(default=datetime.datetime(2021, 8, 13, 4, 58, 3, 792912, tzinfo=utc)),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='projectinfo',
            name='description',
            field=models.TextField(default='description'),
            preserve_default=False,
        ),
        migrations.AlterModelTable(
            name='activitylogs',
            table='Activity Logs',
        ),
        migrations.AlterModelTable(
            name='downloadfile',
            table='DownloadFiles',
        ),
        migrations.AlterModelTable(
            name='fileupload',
            table='FileUpload',
        ),
        migrations.AlterModelTable(
            name='projectusers',
            table='ProjectUsers',
        ),
    ]
