# Generated by Django 3.2.3 on 2021-09-17 05:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('usermanagement', '0004_accessrequest_skill_sets'),
        ('project', '0007_auto_20210813_1028'),
        ('organization', '0006_alter_companyinfo_logo'),
    ]

    operations = [
        migrations.CreateModel(
            name='UsersChannels',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('status', models.BooleanField(default=True)),
                ('channel_id', models.CharField(blank=True, max_length=500, null=True)),
                ('active_from', models.DateTimeField(auto_now_add=True)),
                ('active_upto', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='usermanagement.users')),
            ],
            options={
                'db_table': 'UsersChannels',
            },
        ),
        migrations.CreateModel(
            name='ChatSession',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('session_id', models.CharField(blank=True, max_length=500, null=True)),
                ('isActive', models.BooleanField(default=True)),
                ('created_at', models.DateField(auto_now_add=True)),
                ('updated_at', models.DateField(auto_now=True)),
                ('company', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='organization.company')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='chat_created_by', to='usermanagement.users')),
                ('project', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='project.projectinfo')),
                ('receiver', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='usermanagement.users')),
                ('sender', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='project.projectusers')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='chat_updated_by', to='usermanagement.users')),
            ],
            options={
                'db_table': 'ChatSession',
            },
        ),
        migrations.CreateModel(
            name='ChatHistory',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('message', models.TextField(blank=True)),
                ('status', models.BooleanField(default=True)),
                ('read', models.BooleanField(default=False)),
                ('time_stamp', models.DateTimeField(auto_now_add=True)),
                ('project', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='project.projectinfo')),
                ('session_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='chatbox.chatsession')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='usermanagement.users')),
            ],
            options={
                'db_table': 'ChatHistory',
                'ordering': ['-time_stamp'],
            },
        ),
    ]
