# Generated by Django 3.2.3 on 2021-09-01 09:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('organization', '0006_alter_companyinfo_logo'),
        ('usermanagement', '0005_workers_skill_sets'),
        ('project', '0006_auto_20210810_1037'),
    ]

    operations = [
        migrations.CreateModel(
            name='UsersChannels',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('channel_id', models.CharField(blank=True, max_length=500, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='usermanagement.users')),
            ],
            options={
                'db_table': 'UsersChannels',
            },
        ),
        migrations.CreateModel(
            name='ChatSession',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('session_id', models.CharField(blank=True, max_length=500, null=True)),
                ('isActive', models.BooleanField(default=True)),
                ('created_at', models.DateField(auto_now_add=True)),
                ('updated_at', models.DateField(auto_now=True)),
                ('company', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='organization.company')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='chat_created_by', to='usermanagement.users')),
                ('project', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='project.projectinfo')),
                ('sender', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='project.projectusers')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='chat_updated_by', to='usermanagement.users')),
            ],
            options={
                'db_table': 'ChatSession',
            },
        ),
    ]
