# Generated by Django 3.2.3 on 2021-09-01 12:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0006_auto_20210810_1037'),
        ('usermanagement', '0005_workers_skill_sets'),
        ('chatbox', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChatHistory',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('message', models.TextField(blank=True)),
                ('time_stamp', models.DateTimeField(auto_now_add=True)),
                ('project', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='project.projectinfo')),
                ('session_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='chatbox.chatsession')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='usermanagement.users')),
            ],
            options={
                'db_table': 'ChatHistory',
            },
        ),
    ]
