# Generated by Django 3.2.3 on 2021-09-02 06:53

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('usermanagement', '0005_workers_skill_sets'),
        ('chatbox', '0002_chathistory'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='chathistory',
            options={'ordering': ['-time_stamp']},
        ),
        migrations.AddField(
            model_name='chathistory',
            name='read',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='chathistory',
            name='status',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='chatsession',
            name='receiver',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='usermanagement.users'),
        ),
        migrations.AddField(
            model_name='userschannels',
            name='active_from',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2021, 9, 2, 6, 53, 13, 651200, tzinfo=utc)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='userschannels',
            name='active_upto',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='userschannels',
            name='status',
            field=models.BooleanField(default=True),
        ),
    ]
