# Generated by Django 3.2.3 on 2021-09-02 16:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('usermanagement', '0005_workers_skill_sets'),
        ('chatbox', '0003_auto_20210902_0653'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userschannels',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='usermanagement.users'),
        ),
    ]
